[package]
name = "tranager"
description = "An everything manager for Tea Share"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
colored = "2.0.4"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.106"